baseURL = "https://fity.me"
title = "Fity's Blog"
theme = "PaperModX"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-cn"
copyright = "All rights reserved."
googleAnalytics = "UA-127996141-1"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
TocSide = "right"
env = "production"  # to enable google analytics, opengraph, twitter-cards and schema
title = "Fity's Blog" # will set 'og:site_name'
description = "IT Guy with too much things to learn"
keywords = ["Blog", "Portfolio"]
author = "Fity"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
showtoc = true
tocopen = true
comments = true
disqusShortname = "fityblog"

  [params.homeInfoParams]
    Title = "中年自救记录"
    Content = "一名普通的贫穷码农，什么都不会。人到中年想自救。"

  [params.cover]
    responsiveImages = true
    linkFullImages = true

  [[params.socialIcons]]
    name = "GitHub"
    url = "https://github.com/fity"
  [[params.socialIcons]]
    name = "Email"
    url = "mailto:imfity@gmail.com"
  [[params.socialIcons]]
    name = "RSS"
    url = "/index.xml"

  [params.assets]
    favicon = "/images/favicon.ico"


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[taxonomies]
  author = "Fity"
  tag = "tags"
  category = "categories"
  series = "series"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
# [[menu.main]]
# url = "/posts"
# name = "Archive"
# weight = 3
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 4
[[menu.main]]
url = "/about/"
name = "About"
weight = 5
[[menu.main]]
# url = "/index.xml"
# name = "RSS"
# weight = 6
