baseURL = "https://fity.me"
title = "Fity's Blog"
# theme = "hugo-theme-stack"
DefaultContentLanguage = "zh-cn"      # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-cn"
copyright = "All rights reserved."
# googleAnalytics = "UA-127996141-1"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[languages]

[languages.zh-cn]
disabled = false
languageCode = "zh-cn"
languageName = "ZH"
weight = 0
[languages.zh-cn.params.homeInfoParams]
Title = "中年自救记录"
Content = "一名普通的贫穷码农，什么都不会。人到中年想自救。"

[languages.en]
disabled = false
languageCode = "en"
languageName = "EN"
weight = 1
[languages.en.params.homeInfoParams]
Title = "Wrinkly's poor life"
Content = "A poor wrinkly with nothing useful skills. Here's a birdview of my life."

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"                                   # to enable google analytics, opengraph, twitter-cards and schema
title = "Fity's Blog"                                # will set 'og:site_name'
description = "IT Guy with too much things to learn"
keywords = ["Blog", "Portfolio"]
author = "Fity"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
EnableImageZoom = true
Email = "imfity@gmail.com"
mainSections = ["posts", ]
featuredImageField = "image"
rssFullContent = true
readingTime = true

[params.imageProcessing.cover]
Enabled = true
[params.imageProcessing.content]
Enabled = true

[params.sidebar.avatar]
Enabled = true
Local = true
Src = "images/avatar.jpg"

[params.Author]
email = "imfity@gmail.com"

[params.article]
headingAnchor = true
math = true
# toc = true
readingTime = true

## Widgets
# [[params.widgets.homepage]]
# type = "search"

# [[params.widgets.homepage]]
# type = "archives"

# [[params.widgets.homepage]]
# type = "categories"

[[params.widgets.page]]
type = "toc"

[[widgets.homepage]]
type = "tag-cloud"

[params.artcle.license]
enabled = false
default = "Licensed under CC BY-NC-SA 4.0"

[params.comments]
enabled = true
provider = "waline"
[params.comments.waline]
serverURL = "https://comments.fity.me/"

[params.homeInfoParams]
Title = "中年自救记录"
Content = "一名普通的贫穷码农，什么都不会。人到中年想自救。"

[params.cover]
responsiveImages = true
linkFullImages = true

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/fity"
[[params.socialIcons]]
name = "Email"
url = "mailto:imfity@gmail.com"
[[params.socialIcons]]
name = "RSS"
url = "/index.xml"

[params.assets]
favicon = "/images/favicon.ico"


[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "perldoc"
tabWidth = 4

[taxonomies]
author = "Fity"
tag = "tags"
category = "categories"
series = "series"

[[menu.main]]
url = "/posts"
name = "Posts"
weight = 1
[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
# [[menu.main]]
# url = "/posts"
# name = "Archive"
# weight = 3
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 4
[[menu.main]]
url = "/about/"
name = "About"
weight = 5
[[menu.main]]
# url = "/index.xml"
# name = "RSS"
# weight = 6

[[menu.social]]
identifier = "github"
name = "Github"
url = "https://github.com/fity"
[menu.social.params]
icon = "brand-github"
