[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
GO_VERSION = '1.21.1'
HUGO_VERSION = "0.145.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
GO_VERSION = '1.21.1'
HUGO_VERSION = "0.145.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
GO_VERSION = '1.21.1'
HUGO_VERSION = "0.145.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
GO_VERSION = '1.21.1'
HUGO_VERSION = "0.145.0"

[context.next.environment]
GO_VERSION = '1.21.1'
HUGO_ENABLEGITINFO = "true"
